### ISSUE TITLE
Getting error while installing pod

### ISSUE THREAD

**Issue by KishanVyas** [joncardasis/cocoapods-user-defined-build-types#2]
I follow the installation steps but getting below error while running **pod install** command

> [!] Invalid `Podfile` file: undefined method `enable_user_defined_build_types!' for #<Pod::Podfile:0x00007fad70382fc8>.

**Comment by ghost** [comment]
Could be this issue https://github.com/joncardasis/cocoapods-user-defined-build-types/issues/3

**Comment by joncardasis** [comment]
@KishanVyas You'll get this error if you haven't installed and imported the plugin.
```
gem install cocoapods-user-defined-build-types
```

**Podfile**
```
plugin 'cocoapods-user-defined-build-types'

enable_user_defined_build_types!

target 'NiftyIOSApp' do
  ...
  pod 'Alamofire'
  pod "SwiftyJSON", :build_type => :dynamic_framework
end
```

**Comment by mrgcohen** [comment]
Add to your Gemfile so it works for CI/CD tools
`gem 'cocoapods-user-defined-build-types'`

Then just do with `bundle install`

**Comment by iGroza** [comment]
I'm solved this issue [here](https://github.com/joncardasis/cocoapods-user-defined-build-types/issues/10#issuecomment-878036439)

**Comment by davidtran** [comment]
> Add to your Gemfile so it works for CI/CD tools `gem 'cocoapods-user-defined-build-types'`
> 
> Then just do with `bundle install`

This solution works for me
